### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by adityamahajan-io** [adityamahajan-io/wheel#15]

**Comment by adityamahajan-io** [comment]
@yedhink Deployed the app on Heroku. 
[(https://aditya-neeto-ui.herokuapp.com/)](https://aditya-neeto-ui.herokuapp.com/)

**Comment by yedhink** [comment]
@adityamahajan-io I have added some comments in your PRs. Please fix them and lemme know once done.

**Comment by adityamahajan-io** [comment]
@yedhink I have fixed the code according to the comments. Please have a look.
I will keep the suggestions in mind henceforth. Thanks

**Comment by yedhink** [comment]
@adityamahajan-io LGTM. You can mark this task as completed and go ahead with the next task.

**Comment by adityamahajan-io** [comment]
Okay. Closing this issue. Thanks
